import type { SiteSettings, WishlistItem, Wish, CommunityStory } from "@/lib/types";

export const siteSettingsSeed: SiteSettings = {
  siteTitle: "TOMIDE / 27",
  heroCopy: {
    headline: "27",
    subline: "A lot happened before we got here.",
    supporting: "2016-2026. The story so far.",
    cta: "Start my story",
    skip: "Skip to the birthday",
  },
  birthdayDate: "2026-10-03T12:00:00",
  birthdayTimezone: "Africa/Lagos",
  countdownMode: "countdown",
  birthdayLockMode: false,
  subscriptionsPaused: false,
  social: {
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    twitter: "https://x.com",
    whatsapp: "https://wa.me/",
  },
  wishlistTitle: "27 things I'd love.",
  wishlistCopy: "No pressure. But since you asked… 😌",
  people: [
    {
      id: "p-1",
      name: "[PERSON 01]",
      role: "[RELATIONSHIP / ROLE]",
      sentence: "[ONE SHORT SENTENCE]",
      years: [2024],
    },
    {
      id: "p-2",
      name: "[PERSON 02]",
      role: "[RELATIONSHIP / ROLE]",
      sentence: "[ONE SHORT SENTENCE]",
      years: [2020],
    },
    {
      id: "p-3",
      name: "[PERSON 03]",
      role: "[RELATIONSHIP / ROLE]",
      sentence: "[ONE SHORT SENTENCE]",
      years: [2021],
    },
  ],
  endingGratitude:
    "Thank you for ten years of memories, lessons, laughter, and patience. This is yours as much as it is mine.",
};

export const wishlistSeed: WishlistItem[] = [
  {
    id: "g-1",
    name: "MacBook Pro",
    description:
      "16GB RAM, 512GB or 1TB SSD. M1, M2 or M3. Space Grey or Silver. Start here if the Lord has laid me heavily on your heart.",
    funnyNote: "My laptop has tried. Please let it rest.",
    kind: "expensive",
    sortOrder: 1,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-2",
    name: "Sponsor Me to One African Country",
    description:
      "Pick an African country I haven't experienced, buy the ticket and tell me to pack my bags. I promise to send pictures.",
    funnyNote: "Just buy the ticket and tell me where I'm going.",
    kind: "trip",
    sortOrder: 2,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-3",
    name: "27-inch Curved Monitor",
    description:
      "Samsung or LG preferably. 27 inches because apparently even my monitor needs to respect the birthday theme.",
    funnyNote: "I just want to see my problems on a bigger screen.",
    kind: "expensive",
    sortOrder: 3,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-4",
    name: "₦270,000 Cash Gift",
    description: "₦10,000 × 27 years. For those who believe multiplication is a love language.",
    funnyNote: "If the Lord has placed me heavily on your heart, please don't resist.",
    kind: "cash",
    cashAmount: 270000,
    sortOrder: 4,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-5",
    name: "₦27,000 Cash Gift",
    description: "₦1,000 × 27 years. Simple maths. Beautiful outcome.",
    funnyNote: "Very straightforward. No long explanation needed.",
    kind: "cash",
    cashAmount: 27000,
    sortOrder: 5,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-6",
    name: "₦2,700 Cash Gift",
    description: "₦100 × 27 years. Small, sacred, welcome at this table.",
    funnyNote: "Nobody is too small to participate in this ministry.",
    kind: "cash",
    cashAmount: 2700,
    sortOrder: 6,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-7",
    name: "27 Books for 27",
    description:
      "Curate 27 books for me. Faith, business, biographies, psychology, marketing, technology, novels, anything brilliant. Basically, build me a small library.",
    funnyNote: "Please, good books. Don't use me to clear your shelf.",
    kind: "multi",
    sortOrder: 7,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-8",
    name: "Your Favourite Novel + A Note",
    description:
      "Buy me your favourite novel and write inside why you love it and why you think I should read it. I want a little piece of your brain on my bookshelf.",
    funnyNote: "Give me one book you'll actually disturb me to read.",
    kind: "multi",
    sortOrder: 8,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-9",
    name: "Artwork & Wall Frames",
    description:
      "My walls deserve better. Paintings, prints, African art, abstract pieces, beautiful frames. Help me give the house some personality.",
    funnyNote: "My walls are currently going through a lot.",
    kind: "multi",
    sortOrder: 9,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-10",
    name: "A Completely Custom Gift",
    description:
      "Make me something that literally belongs to nobody else. Portrait, engraving, illustration, clothing, journal, sculpture, anything. Creativity gets extra points.",
    funnyNote: "Just make me something nobody else has.",
    kind: "multi",
    sortOrder: 10,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-11",
    name: "A Proper Spa & Massage Day",
    description:
      "Book it. Send me the details. I'll show up and allow strangers to remove 27 years of stress from my body.",
    funnyNote: "This body has worked very hard this year.",
    kind: "single",
    sortOrder: 11,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-12",
    name: "A Weekend Vacation",
    description:
      "Two or three nights somewhere beautiful. No conference. No work trip. No 'quick meeting while you're there.' I want to disappear responsibly.",
    funnyNote: "Please send me somewhere nobody can ask me for a quick call.",
    kind: "expensive",
    sortOrder: 12,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-13",
    name: "An Experience I've Never Had",
    description:
      "Theatre, boat cruise, pottery, horse riding, go-karting, paint and sip or something I wouldn't normally book for myself. Expand my lore.",
    funnyNote: "Just don't book anything that can kill me.",
    kind: "multi",
    sortOrder: 13,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-14",
    name: "Take Me on a Dinner Date",
    description:
      "Pick somewhere beautiful, make the reservation and tell me what time to arrive. I'll bring appetite and conversation.",
    funnyNote: "You pick the place. I'll come hungry.",
    kind: "multi",
    sortOrder: 14,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-15",
    name: "A Really Good Pair of Headphones",
    description:
      "Something with excellent sound and proper noise cancellation. For flights, deep work, music and occasionally pretending the rest of the world does not exist.",
    funnyNote: "Sometimes I just don't want to hear anybody.",
    kind: "single",
    sortOrder: 15,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-16",
    name: "Wardrobe Upgrade",
    description:
      "One piece, two pieces, five pieces, an entire outfit. Shirts, trousers, polos, jackets, native wear, sneakers. Help the birthday boy dress like his future tax bracket.",
    funnyNote: "Help me dress like the money is already here.",
    kind: "multi",
    sortOrder: 16,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-17",
    name: "Apple Watch",
    description:
      "Doesn't have to be the latest one. It just needs to work beautifully with my iPhone and occasionally remind me that I have, once again, not stood up for six hours.",
    funnyNote: "Maybe if my watch tells me to stand up, I'll finally listen.",
    kind: "expensive",
    sortOrder: 17,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-18",
    name: "A Really Good Perfume",
    description:
      "Don't ask me what I want. Smell something and think, 'This is dangerously Tomide.' Buy that one.",
    funnyNote: "I want to enter the room before I enter the room.",
    kind: "multi",
    sortOrder: 18,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-19",
    name: "Something Beautiful for My Workspace",
    description:
      "Lamp, sculpture, plant, clock, organizer or a beautiful desk object. I spend too much time there for it not to look expensive.",
    funnyNote: "I spend half my life there. It should at least look good.",
    kind: "multi",
    sortOrder: 19,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-20",
    name: "Something Really Good for My Kitchen",
    description:
      "Chef's knife, cast-iron pan, Dutch oven, air fryer, blender, cookware, beautiful chopping board. I love cooking, so come and enable the behaviour.",
    funnyNote: "Anything that will encourage this cooking habit.",
    kind: "multi",
    sortOrder: 20,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-21",
    name: "A Cooking Class",
    description:
      "Book me a proper hands-on cooking class. Pasta, sushi, pastry, steak, African cuisine, anything interesting. Let me add another unnecessary culinary skill to my résumé.",
    funnyNote: "As if I don't already have enough things I'm trying to learn.",
    kind: "multi",
    sortOrder: 21,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-22",
    name: "Flowers for Me",
    description:
      "Yes. Me. Flowers. A proper beautiful bouquet too. Men deserve to randomly stare at flowers on their table and smile.",
    funnyNote: "Yes, I'm a man. Yes, send the flowers.",
    kind: "multi",
    sortOrder: 22,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-23",
    name: "A Hamper of Random Things I Like",
    description:
      "No corporate hamper please. Build it yourself. Snacks, chocolates, drinks, grooming stuff, little gifts, weird things that remind you of me. Chaos, but thoughtful chaos.",
    funnyNote: "Just put plenty of things inside. I like opening things.",
    kind: "multi",
    sortOrder: 23,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-24",
    name: "Sponsor NEXORA for 27 People",
    description:
      "Instead of buying something for me, give 27 people access to something I built. Now that would make me smile.",
    funnyNote: "This one will actually make me very happy.",
    kind: "multi",
    sortOrder: 24,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-25",
    name: "Bless Someone Because I Turned 27",
    description:
      "Find someone who genuinely needs something and sort it out. Food, transport, books, school fees, data, business support, anything. Just tell them somebody turned 27 and apparently that became their business too.",
    funnyNote: "Do something good for somebody and blame my birthday.",
    kind: "multi",
    sortOrder: 25,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-26",
    name: "Write Me a Handwritten Letter",
    description:
      "Actual pen. Actual paper. No ChatGPT, please. Tell me what you've watched me become, something I need to hear and what you're praying for me as I enter 27.",
    funnyNote: "And please, I'll know if ChatGPT wrote it.",
    kind: "multi",
    sortOrder: 26,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-27",
    name: "27 of Something",
    description:
      "This one is completely yours. 27 flowers. 27 chocolates. 27 pictures. 27 Bible verses. 27 prayers. 27 memories. 27 tiny gifts. 27 voice notes. Surprise me. There is only one rule: make it 27.",
    funnyNote: "Anything you like. Just count it properly.",
    kind: "multi",
    sortOrder: 27,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "g-28",
    name: "Anything Else You Can Afford",
    description:
      "This list is for fun, not a rulebook. If none of the 27 works for you, get me anything else you can afford and genuinely want to give me. Big, small, random, thoughtful, useful or completely unserious. If it came from you with love, I'll appreciate it.",
    funnyNote: "This is a wishlist, not a church project. Give what you can.",
    kind: "multi",
    sortOrder: 28,
    status: "active",
    createdAt: "2026-09-01T00:00:00Z",
  },
];

export const wishesSeed: Wish[] = [
  {
    id: "w-seed-1",
    senderName: "A friend from the start",
    relationship: "friends",
    message:
      "Those ten years went fast. May the next chapter be the one you look back on and smile hardest about. Happy birthday, Tomide.",
    anonymous: false,
    status: "published",
    createdAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "w-seed-2",
    senderName: "Anonymous",
    relationship: undefined,
    message: "Whatever 27 brings, I hope it brings you peace and good people. You deserve both.",
    anonymous: true,
    status: "published",
    createdAt: "2026-09-21T14:30:00Z",
  },
];

export const storiesSeed: CommunityStory[] = [
  {
    id: "s-seed-1",
    senderName: "Chidera Okafor",
    meetingContext: "Babcock University",
    title: "The night we almost burnt the hostel kitchen",
    body:     "It was 2019, first semester, and someone had the idea that we should cook jollof at 2am because nobody could sleep. Tomide was the only one sober enough to guard the pot, and he took that job ridiculously seriously.\n\nLong story short, the oil caught fire. Everyone scattered like cockroaches. Tomide stood there, grabbed the pot lid, dropped it flat on the flames, and calmly said, you people should just sit down. No burn, no alarm, no drama. The jollof was actually perfect.\n\nWe ate that rice at 3am and talked about everything we wanted to become. He was already that boy back then. The one who keeps his head when everyone else is losing theirs.",
    year: 2019,
    funnyPromptAnswer:       "He will deny being scared, but his hands were shaking for a full five minutes after the fire.",
    photos: [],
    status: "published",
    featured: false,
    createdAt: "2026-09-19T09:00:00Z",
  },
  {
    id: "s-seed-2",
    senderName: "Tunde Adeyemi",
    meetingContext: "First job, Lagos",
    title: "The money that disappeared and reappeared",
    body:     "Fresh employees got paid late that first month and the entire office was on edge. Tomide was the only person who stayed completely calm, and I remember thinking this guy must have hidden money somewhere.\n\nTurns out he just had a habit of keeping a notebook with every single expense written down. Kobo by kobo. When the salary finally landed, he took two of us out for suya and said, salary is a promise. Your system is what keeps it.\n\nThat stuck with me longer than any training in that office. The man does not wing life. He plans it, then enjoys it.",
    year: 2021,
    funnyPromptAnswer:       "He will deny that his exam was a legit budget, but his note is prettier than most financial documents I have seen.",
    photos: [],
    status: "published",
    featured: false,
    createdAt: "2026-09-20T11:30:00Z",
  },
];